### ISSUE TITLE
[Story] Brainstorm UI updates to make the app more slick by end of April

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1350]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a developer of OpenChallenges, I want the UI to be more slick for the launch of the private preview so that the app becomes more impactful.

### Description

For each page and component, identify UI improvements that can positively contribute to the UX of the beta testers.

### Acceptance criteria

- A list of UI improvements has been identified.
- The item in the list are classified with the [MoSCoW](https://en.wikipedia.org/wiki/MoSCoW_method) for the launch of the private preview.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Increased the priority of this ticket to High: the sooner we have identified UI improvements the sooner we can implement them.

**Comment by vpchung** [comment]
## Weekly Update

I plan to start on this tomorrow.

**Comment by vpchung** [comment]
## General

- [ ] As suggested by Stockard from the Design team, we should stick with the cooler-toned colors to be "more flexible for different people looking at it - pink tones [are] more biased".
    - [ ] Remove the pink and orange color palettes perhaps?
- [ ] Maybe remove the uppercase text transformations...? Not a big fan of the look, now that we are using Lato.
- [ ] Be consistent with text sizes used, e.g. navbar text is _tiny_ compared to the rest of the app
- [ ] Replace all "Registry of Open Community Challenges" and "ROCC" with "OpenChallenges"

## Navbar component

- [ ] Increase text size
- [ ] Increase logo size
- [ ] In the dropdown, either remove all icons, or find icons for "My Challenges" and "My Organizations"

## Footer component

- [ ] As suggested above, remove uppercase transformation from the hyperlinks


## Home page

- [ ] Add some sort of icon or avatar to the topic card - they look a little lifeless
    - [ ] ^ maybe even remove this section? (since we're not showing keywords/tags yet)
- [ ] Add image to "Are you a challenge organizer" section
    - [ ] Have the button link to something, maybe the Google sheet or a Loom video?

## About page

- [ ] In the Goals section, maybe do a table instead of cards?
- [ ] Increase text size (the difference between the headers and paragraphs is kind of comical 😆 )

## Meet the Team page

 - [ ] Fix skewed heights/widths of images
 - [ ] Add Maria as a contributor

## Search pages

- [ ] Increase text size
- [ ] Remove the paginator for 0 results (either that or "sticky" it to the bottom)

![Image](https://user-images.githubusercontent.com/9377970/228433498-6fa79ba7-9a3e-4fcc-b41b-a9329d830d73.png)

## Profile pages

- [ ] Remove uppercase text transformation for the header titles (use bold instead?)
- [ ] Hide paginator for empty Challenges and Starred sections
- [ ] The Starred tabs should use Lato, not Arial 
- [ ] Increase text size of the non-header texts

## Login page

- [ ] Use the official OC logo
- [ ] Increase text size (of inputs and buttons)

## Card components

- [ ] (specifically for challenge-card) use a different placeholder image color (something cooler-toned)

**Comment by vpchung** [comment]
Starting list has been compiled, so I will close this ticket now.

I will track actual implementations in a separate ticket.
