### ISSUE TITLE
Validate the query when searching for challenges and organizations

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/sage-monorepo#1397]
For the current frontend approach, any query (e.g. `{foo: "bar"}`) will be also added to the query, which might cause errors if invalid query was sent to api service.

- [ ] Add validation on the query name for `challenge-search` and `org-search` pages to capture errors while developing the app.

**Comment by tschaffter** [comment]
Unknown query parameters sent to the organization service, for instance, are ignored. This is in line with the expectation that a user of the REST API may generate a request with unknown parameters and the service should not record that as an error (we will be monitoring errors so that would be considered a false positive).

Today we bumped into a case where the app sent a request with an object that did not match an outdated definition of `OrganizationSearchQuery`. Ideally, the TypeScript language service or the compiler should have let the developer know that the object created did not match the interface `OrganizationSearchQuery`, which would have prompted the developer to investigate and realize that the OC client for Angular for outdated.

The solution should ideally be a type check, maybe using a type guard, that the TS language service would highlight immediately or a type check that fails when the compiler build the app. Anything more complicated is probably not worth the trouble. Alternatively, we should also write unit tests at some point, which would fail the CI/CD workflow.

**Comment by tschaffter** [comment]
Added to Backlog
