### ISSUE TITLE
[Story] Enable reproducible spreadsheet-to-sql workflow

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1453]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a developer, I want to know how I can update the content of the OC database (SQL files), so that I can contribute to the collection of the OC data.

### Description

TBD (@vpchung )

### Acceptance criteria

- Developer should be able to run commands to update the SQL file

### Tasks

TBD (@vpchung )

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Notes from a discussion with @vpchung 

Two options:
1. Query Google sheet directly (preferred)
  - Do we need an API key even if the doc is public?
3. Download the sheet and have the script clean it up.

How to get started:
1. Create an app: copy `scr/schematic/api` folder and place it in `apps/openchallenges`
2. Remove all files that are not needed
3. Review `project.json`
4. Run the first three commands of the task `prepare-python` manually to initialize the Python environment
5. Remove all poetry files and run `poetry init`
6. Create a task in `project.json` that execute `poetry run python <script>`

**Comment by tschaffter** [comment]
Move to Sprint 23.07

**Comment by tschaffter** [comment]
Setting this story to High priority. Let's aim to get this story done in the first half of next sprint (23.07).

**Comment by tschaffter** [comment]
Moved to Sprint 23.08.

**Comment by tschaffter** [comment]
Returned to Backlog

**Comment by vpchung** [comment]
## Oct sprint update

I have successfully updated my local script so that it utilizes [`gspread`](https://docs.gspread.org/en/v5.10.0/) to pull information directly from the [OC Google Sheet](https://docs.google.com/spreadsheets/d/1XRSUVqbZk_k9_rV1vpgPVMQ0fVV0mavwY8Aqyy0C2HQ/edit#gid=1834177142), clean up the data, and export them as CSVs.

In order to use `gspread` (and any Google APIs in general), I first created a service account for the OC. The service account is currently under my account on GCP, using the email: `openchallenges-data@openchallenges-402004.iam.gserviceaccount.com`.  I also double-checked and made sure that using the Google Drive API and Google Sheets API services are free - they are both free so long as we don't go crazy with the number of requests.

Next steps are to transfer the script over to the monorepo as a new project/app.

**Comment by vpchung** [comment]
Phew, glad we can finally close this 😅
