### ISSUE TITLE
[Bug] Unable to access the app at port `8000` when using the development server of app

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/sage-monorepo#1764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

The  page (`http://localhost:8000/)` should be redirected to the app port (`4200`) using development mode (`nx serve openchallenges-app`)  based on the configuration in _apex_. However, the page shows "502 Gateway Error" on the `http://localhost:8000/`, whereas the _zipkin_ (`http://localhost:8000/zipkin`) and _api-gateway_ (e.g. `http://localhost:8000/api/v1/challenges`) still work.

The app can be accessed using the container of the app (`nx serve-detach openchallenges-apex`). 

### Expected behavior

Developers should be able to access the app using development mode at port `8000`.

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
The issue is related to how the Apex, which is an Nginx reverse proxy, handles the host names of the component. Here are the host names and port that we define in the `.env` of the apex:

```
API_GATEWAY_HOST=openchallenges-api-gateway
API_GATEWAY_PORT=8082
APP_HOST=openchallenges-app
APP_PORT=4200
THUMBOR_HOST=openchallenges-thumbor
THUMBOR_PORT=8889
ZIPKIN_HOST=openchallenges-zipkin
ZIPKIN_PORT=9411
```

When starting the Apex, the container `openchallenges-app` is started first because we defined that the apex depends on the app container. When the apex container then starts, Docker translates the host name `openchallenges-app` to the Docker IP address of the app container. if the app container no longer exists and we start the app in development mode, the apex will still forward the requests to a Docker IP that is no longer valid, hence the Bad Gateway issue.

Apex fails to start when its Nginx config still references `openchallenges-app` WHILE the app container is not running. In the example below, we have removed the dependency of the Apex container on the app container in the Docker Compose file of the apex, so the app container is not running when starting apex.

```console
$ nx serve-detach openchallenges-apex
$ docker logs -f openchallenges-apex
...
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/events.conf.template to /etc/nginx/conf.d/events.conf
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/http.conf.template to /etc/nginx/conf.d/http.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/07/12 23:34:58 [emerg] 1#1: host not found in upstream "openchallenges-app:4200" in /etc/nginx/conf.d/http.conf:11
nginx: [emerg] host not found in upstream "openchallenges-app:4200" in /etc/nginx/conf.d/http.conf:11
```

The logs show that the upstream "openchallenges-app:4200" could not be found. The same error occurs if the app server runs in development mode when the apex is started.

## This issue does not affect backend services

The follow works:

- Start the stack with `nx serve-detach openchallenges-apex`
- Remove the container of the challenge service with `docker rm -f openchallenges-challenge-service`
- Start the challenge service in development mode with `nx serve openchallenges-challenge-service`
- Try to access `localhost:8000/api/v1/challenges` still works

The reason is because the Apex sends the requests to the backend via the API gateway. The API gateway then sends the request to the services. Because we don't touch to the API gateway, the apex has no issue. Moreover, it does not matter to the API gateway whether the challenge service is running with its development server or with its container.

## Solution

I need to do some exploration work to enable the apex container to access the development server of the app. It shouldn't be a blocker for development for now, as we should still be able to access the development server of the app on `localhost:4200`.

**Comment by tschaffter** [comment]
@rrchai I don't think that there is a simple solution to this "issue". I've came across a [few solutions](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach) but they may necessarily increase the complexity of the dev environment.

When running the development server of the web app, the idea is to access it on the port the dev server exposes instead of the apex port (`8000`). This approach should work perfectly fine. If you bump into an issue, feel free to reopen this ticket or open a new one.
