### ISSUE TITLE
[Enhancement] Revisit facets to highlight on Challenge Search page

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1831]
## Sage Design feedback

Current list of facets on Challenge Search:

![Image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/c14b97b2-bd2e-4fb8-ad90-5daa28f0a494)

By default, "Challenge Year", "Status", and "Input Data Type" are open, which assumes that these facets will be used the most frequently.  However, _will_ "Challenge Year" be used as often as the other facets? i.e. is it expected that users will want to look at older challenges when they first visit OC?  Or will they be more interested in the ones currently running?

What about "Incentive Type" or "Submission Type" instead?

**Comment by tschaffter** [comment]
I agree with Adam: we should have a discussion about the importance of the filters and order them based on this importance. Here is my suggestion:

- Status
- Incentive
- Year
- Platform
- and then the rest

In the future, analytics data could help us reorganize the order of the filters - though we shouldn't change them often otherwise the users will lose their footing.
