### ISSUE TITLE
[Feature] Collect feedback on generating OC Data Completeness

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1854]
### What projects is this feature for?

OpenChallenges

### Description

Upcoming work related to code coverage made me think that we could report a similar metric for OC data, namely OC data coverage?

Code coverage is computed as the percentage of testable lines that are executed by tests.

Similarly, we could reported on the percentage of {challenge,organization} fields that are not null/empty.

Generating this metric could be useful to report internally on data collection effort. Increasing this metric could also help data submitter visualizes how their submission positively contributes to increasing the comprehensiveness of OC challenge data.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thomasyu888** [comment]
@tschaffter I would call this "data completeness" instead of "data coverage".  I think data coverage could mean how your data represents a population, while data completeness is how much "expected data" is present in your dataset.

A low completeness score would mean you have many missing or null values
