### ISSUE TITLE
[Feature] Revisit challenge card designs for those with longer titles

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1948]
### What projects is this feature for?

OpenChallenges

### Description

Challenge cards with long titles (span over 3+ lines) doesn't look too great, e.g.

![Screenshot 2023-08-08 at 10 36 16 PM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/a7b0bdbc-516c-4612-b987-5ec5718a95ae)

We could either:
* increase the card height
* overwrite the line height set for the card-title
* set a character limit for the card title
* hide the platform information if the title is too long

Of these, I like option 2 the best, followed by 1 or 3.  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rrchai** [comment]
I agree to just adjust the title height since we already have max character limits (`60`) for challenge name.

**Comment by tschaffter** [comment]
This challenge title spread over 4 lines. We probably don't want titles to spread on so many lines.

https://openchallenges.io/challenge/110/oropharynx-radiomics-hpv

Ideas:
- Slightly decrease the font size
- Fix the height of the title section so that only three lines are displayed.
  - The three lines displayed are probably enough to uniquely identify the challenge.

**Comment by rrchai** [comment]
> This challenge title spread over 4 lines. We probably don't want titles to spread on so many lines.

The challenge name is 92 chars. Is it a bug?
https://github.com/Sage-Bionetworks/sage-monorepo/blob/9807dd9a5b68a6c2796b6994231e5e2377bd0692/libs/openchallenges/api-description/src/components/schemas/ChallengeName.yaml#L1-L4
