### ISSUE TITLE
[Bug] Troubleshoot Schematic failed tests reported by Andrew in `main`

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

Schematic

### Current behavior

See this [comment](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2507#issuecomment-1967798749) by @andrewelamb.

One question is why the errors reported where not detected in the last commit to `main` that modified Schematic.

### Commit ID

70f2f7bf11fab89653d0805b4c04b5656f8dce3c

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrewelamb** [comment]
Ok so the problem is [this.](https://github.com/Sage-Bionetworks/sage-monorepo/blob/main/apps/schematic/api/schematic_api/test/conftest.py#L81C1-L81C118)

The datamodel used for testing is part fo scchematic repo. In schematic v24.2.1, there were breaking changes to some methods and the data model. Updating to v24.2.1 will fix this as per [this pr.](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2533)

**Comment by andrewelamb** [comment]
The reason there were no errors the last time the API was updated, was that the changes to the linked data model hadn't been pushed to main yet.

**Comment by andrewelamb** [comment]
The short term fix is to get that PR merged into main. The long term fix is to link to a data model  in its own repo, not part of schematic.

**Comment by tschaffter** [comment]
Done
