### ISSUE TITLE
[Bug] Fix task `agora-data:publish-image`

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

Agora

### Current behavior

The CI/CD workflow fails to push the image during the task `agora-data:publish-image` to GHCR. The new "version" tags is pushed but not `edge`.

Workflow logs: https://github.com/Sage-Bionetworks/sage-monorepo/actions/runs/9688567621/job/26740065572

Package on GHCR: https://github.com/Sage-Bionetworks/Agora/pkgs/container/agora-data

cc @hallieswan 

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hallieswan** [comment]
The workflow fails with the following error: 

```
#15 ERROR: denied: permission_denied: write_package
------
 > pushing ghcr.io/sage-bionetworks/agora-data:edge with docker:
------
ERROR: denied: permission_denied: write_package

>  Removing temp folder /tmp/docker-build-push-GTWlpr 


 NX   buildx failed with: ERROR: denied: permission_denied: write_package
```

Since we created the `agora-data` package from the current `Sage-Bionetworks/Agora` repo, the `Sage-Bionetworks/sage-monorepo` action doesn't have Actions access to the package and the workflow can't push a new image to the package.

Plan to fix:
1. Delete the current `agora-data` package owned by `Sage-Bionetworks/Agora`
2. Re-run sage-monorepo [workflow](https://github.com/Sage-Bionetworks/sage-monorepo/actions/runs/9688567621/job/26740065572) - `agora-data` package should be created, owned by `Sage-Bionetworks/sage-monorepo`, and contain all image tags
3. Change package name in `Sage-Bionetworks/Agora` workflow to `agora-data-e2e`

**Comment by hallieswan** [comment]
The `agora-data` package now includes sha, edge, and data release version tags for images built by the sage-monorepo workflow.
